# import the python datetime module to help us create a timestamp
from glass_tank import Snake
from petting_area import Petting_area_animal
from pond import Water_animal
from aviary import Bird


buckey = Petting_area_animal("Buckey", "beaver", "North American Beaver", "morning")
felix = Water_animal("Felix", "catfish", "Flathead Catfish")
figaro = Water_animal("Figaro", "catfish", "Blue Catfish")
garfield = Water_animal("Garfield", "catfish", "Channel Catfish")
drumstick = Bird("Drumstick", "chicken", "Rhode Island Red Chicken")
kung_pao = Bird("Kung Pao", "chicken", "Rhode Island Red Chicken")
margaret = BaseException("Margaret Hatcher", "chicken", "Barred Plymouth Rock Chicken")
medusa = Snake("Medusa", "copperhead snake", "Northern Copperhead")
dominick = Petting_area_animal("Dominick", "donkey", "miniature donkey", "midday")
daffy = Bird("Daffy", "duck", "Gadwell")
donald = Bird("Donald", "duck", "American Black Duck")
daisy = Bird("Daisy", "duck", "Blue Winged Teal")
david = Bird("David", "duck", "Mallard")
pilot = BaseException("Pilot", "eagle", "Bald Eagle")
buzz = Bird("Buzz", "eagle", "Golden Eagle")
norman = Petting_area_animal("Norman", "goat", "Boehr", "afternoon")
vincent = Petting_area_animal("Vincent van Goat", "goat", "pygmy goat", "morning")
scape = Petting_area_animal("Scape Goat", "goat", "fainting goat", "afternoon")
butt_head = Petting_area_animal("Butt-Head", "goat", "Alpine goat", "morning")
billy = Petting_area_animal("Billy the Kid", "goat", "LaMancha goat", "afternoon")
finny = Water_animal("Finny", "goldfish", "Common Goldfish")
splash = Water_animal("Splash", "goldfish", "Common Goldfish")
heroninon = Bird("Heroninon", "heron", "Great Blue Heron")
theron = Bird("Theron", "heron", "Grey Heron")
sheron = Bird("Sheron", "heron", "Pacific Heron")
jafar = Snake("Jafar", "kingsnake", "California Mountain Kingsnake")
bashful = Water_animal("Bashful", "koi", "Kohaku Koi")
flirtatious = Water_animal("Flirtatious", "koi", "Taisho Sanshoku")
kitten = Water_animal("Kitten", "koi", "Showa Sanshoku")
reticent = Water_animal("Reticent", "koi", "Showa Sanshoku")
skittish = Water_animal("Skittish", "koi", "Taisho Sanshoku")
carp_e_diem = Water_animal("Carpe-e-Diem", "koi", "Kohaku Koi")
snowflake = Petting_area_animal("Snowflake", "lamb", "Australian White", "morning")
alan = Petting_area_animal("Alan", "lamb", "Hampshire Sheep", "afternoon")
miss_fuzz = Petting_area_animal("Miss Fuzz", "llama", "Domestic Llama", "midday")
al = Petting_area_animal("Al", "llama", "Alpaca", "morning")
boots = Petting_area_animal("Boots", "llama", "Wooly llama", "afternoon")
rainbow = Bird("Rainbow", "peacock", "Indian Peafowl")
nancy = Bird("Nancy Beth Carlson", "peacock", "Green Peafowl")
piglet = Petting_area_animal("Piglet", "pig", "Hanford Mini Swine", "morning")
waddles = Petting_area_animal("Waddles", "pig", "American Mini Pig", "afternoon")
wilber = Petting_area_animal("Wilber", "pig", "Mulefoot Hog", "midday")
miss_piggy = Petting_area_animal("Miss Piggy", "pig", "Ossabaw Island Hog", "morning")
piggly_wiggly = Petting_area_animal("Piggly Wiggly", "pig", "Meishan Breed Pig", "afternoon")
porky = Petting_area_animal("Porky", "pig", "Juliana Breed Pid", "afternoon")
bacon = Petting_area_animal("Bacon", "pig", "Pot-Bellied Pig", "morning")
slinky = Snake("Slinky", "python", "Indian Python")
basil = Snake("Basil", "rat snake", "Eastern Rat Snake")
slithers = Snake("Slithers", "rattlesnake", "Eastern Diamondback")
rattles = Snake("Rattles", "rattlesnake", "Prairie Rattlesnake")
paul_bunyon = Snake("Paul Bunyon", "rattlesnake", "Timber Rattlesnake")
diablo = Snake("Diablo", "rattlesnake", "Horned Rattlesnake")
crush = Water_animal("Crush", "turtle", "Common Snapping Turtle")
squirtle = Water_animal("Squirtle", "turtle", "Mississippi Map Turtle")
roberto = Petting_area_animal("Roberto", "llama", "Alpaca", "morning")

print(f'{roberto.name} the {roberto.species} is available to pet during the {roberto.shift} shift.')